// generated by port.py: each PC wallpaper's alternate (shift-click in Cobblemon), by its code
export const PC_ALT_WALLS = {"w01": "x01", "w02": "x02", "w03": "x03", "w04": "x04", "w05": "x05", "w06": "x06", "w07": "x07", "w08": "x08", "w09": "x09", "w10": "x10", "w11": "x11", "cav": "xcv", "for": "xfr", "nth": "xnt", "ocn": "xoc", "end": "xen", "alp": "xal"};
